model:
  type: gcn
  in_dim: 7
  hidden: 64
  out: 2
clients:
  n_clients: 5
  non_iid: false
fedbn:
  enabled: true
hetero:
  enable_distillation: false
comm:
  compress: none  # options: none, topk, int8
  topk_ratio: 0.01
dp:
  enabled: false
  clip_norm: 1.0
  noise_multiplier: 0.5
privacy:
  delta: 1e-5
  accounting: rdp
local:
  epochs: 1
  local_steps: 10
  batch_size: 8
  lr: 0.01
robust:
  method: null  # options: null, trimmed_mean, krum
  trimmed_ratio: 0.1
  byzantine_clients: 1
pFedMe:
  enabled: false
